# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 01:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codestreak.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('uuid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('streak', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('utc_offset', models.PositiveIntegerField(default=0)),
                ('lost', models.BooleanField(default=False)),
                ('sessions', models.ManyToManyField(to='codestreak.Session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
