# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codestreak', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streak',
            name='uuid',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
    ]
