# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-03 13:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codestreak', '0002_streak_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='streak',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 3, 14, 57, 9, 956202)),
        ),
    ]
