# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-03 19:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codestreak', '0003_auto_20170103_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='streak',
            name='utc_offset',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='streak',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 3, 20, 54, 28, 454227)),
        ),
    ]
