# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-07 00:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codestreak', '0006_auto_20170103_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=datetime.datetime(2017, 1, 7, 0, 59, 56, 754341))),
                ('end', models.DateTimeField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codestreak.Language')),
            ],
        ),
        migrations.RemoveField(
            model_name='streak',
            name='id',
        ),
        migrations.AddField(
            model_name='streak',
            name='uuid',
            field=models.TextField(default='iXaWxmWKd61HoYE3qGUVcrRYAUy6HBbH', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='streak',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 7, 0, 59, 56, 754843)),
        ),
        migrations.AddField(
            model_name='streak',
            name='sessions',
            field=models.ManyToManyField(to='codestreak.Session'),
        ),
    ]
