# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-01 15:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codestreak', '0007_auto_20170107_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 1, 16, 39, 39, 218582)),
        ),
        migrations.AlterField(
            model_name='streak',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 1, 16, 39, 39, 219082)),
        ),
        migrations.AlterField(
            model_name='streak',
            name='uuid',
            field=models.TextField(default='fQJCyfqxaCYmUIhF86C8CDBiR5dwjqoU', max_length=32, primary_key=True, serialize=False),
        ),
    ]
