# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 00:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codestreak', '0008_auto_20170201_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 7, 1, 12, 52, 276027)),
        ),
        migrations.AlterField(
            model_name='streak',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='streak',
            name='streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='streak',
            name='utc_offset',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='streak',
            name='uuid',
            field=models.CharField(default='2jlRrZFxcf', max_length=10, primary_key=True, serialize=False),
        ),
    ]
