# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 00:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codestreak', '0009_auto_20170207_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 7, 1, 43, 45, 933966)),
        ),
        migrations.AlterField(
            model_name='streak',
            name='uuid',
            field=models.CharField(default='4zvS3fezvx', max_length=10, primary_key=True, serialize=False),
        ),
    ]
