# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codestreak', '0010_auto_20170207_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='streak',
            name='uuid',
            field=models.CharField(default='io4UwT08tF', max_length=10, primary_key=True, serialize=False),
        ),
    ]
