# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codestreak', '0011_auto_20170207_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streak',
            name='uuid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
